"""initial schema

Revision ID: de80a0d590de
Revises: 
Create Date: 2026-02-27 23:08:00.833842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de80a0d590de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_verifications_email', 'email_verifications', ['email'], unique=False)
    op.create_index('idx_email_verifications_expires_at', 'email_verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=True)
    op.create_index(op.f('ix_email_verifications_id'), 'email_verifications', ['id'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hotels_city', 'hotels', ['city'], unique=False)
    op.create_index('idx_hotels_created_at', 'hotels', ['created_at'], unique=False)
    op.create_index('idx_hotels_location', 'hotels', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_hotels_price', 'hotels', ['price'], unique=False)
    op.create_index('idx_hotels_rating', 'hotels', ['rating'], unique=False)
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_name'), 'hotels', ['name'], unique=False)
    op.create_index(op.f('ix_hotels_price'), 'hotels', ['price'], unique=False)
    op.create_index(op.f('ix_hotels_rating'), 'hotels', ['rating'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('check_in_date', sa.String(length=10), nullable=False),
    sa.Column('check_out_date', sa.String(length=10), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('total_payable', sa.Float(), nullable=True),
    sa.Column('price_snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index('idx_bookings_created_at', 'bookings', ['created_at'], unique=False)
    op.create_index('idx_bookings_dates', 'bookings', ['check_in_date', 'check_out_date'], unique=False)
    op.create_index('idx_bookings_hotel_id', 'bookings', ['hotel_id'], unique=False)
    op.create_index('idx_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('idx_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookings_booking_id'), 'bookings', ['booking_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('activity_event', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_activity_action_type', 'user_activity', ['action_type'], unique=False)
    op.create_index('idx_user_activity_timestamp', 'user_activity', ['timestamp'], unique=False)
    op.create_index('idx_user_activity_user_action', 'user_activity', ['user_id', 'action_type'], unique=False)
    op.create_index('idx_user_activity_user_id', 'user_activity', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_activity_action_type'), 'user_activity', ['action_type'], unique=False)
    op.create_index(op.f('ix_user_activity_id'), 'user_activity', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_timestamp'), 'user_activity', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activity_timestamp'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_action_type'), table_name='user_activity')
    op.drop_index('idx_user_activity_user_id', table_name='user_activity')
    op.drop_index('idx_user_activity_user_action', table_name='user_activity')
    op.drop_index('idx_user_activity_timestamp', table_name='user_activity')
    op.drop_index('idx_user_activity_action_type', table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_id'), table_name='bookings')
    op.drop_index('idx_bookings_user_id', table_name='bookings')
    op.drop_index('idx_bookings_status', table_name='bookings')
    op.drop_index('idx_bookings_hotel_id', table_name='bookings')
    op.drop_index('idx_bookings_dates', table_name='bookings')
    op.drop_index('idx_bookings_created_at', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hotels_rating'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_price'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_name'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_index('idx_hotels_rating', table_name='hotels')
    op.drop_index('idx_hotels_price', table_name='hotels')
    op.drop_index('idx_hotels_location', table_name='hotels')
    op.drop_index('idx_hotels_created_at', table_name='hotels')
    op.drop_index('idx_hotels_city', table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_index('idx_email_verifications_expires_at', table_name='email_verifications')
    op.drop_index('idx_email_verifications_email', table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
